"""
Language translations for the ProfFinder application.
Supports English and Korean.
"""

TRANSLATIONS = {
    "en": {
        # Main UI
        "app_title": "🎓 Professor Finder - Graduate Advisor Discovery",
        "app_subtitle": "Welcome, Shin Ha Eun! Find your perfect graduate advisor based on research expertise and availability",
        "language_toggle": "Language",
        
        # Search Form
        "search_form_title": "🔍 Search Parameters",
        "keywords_label": "Research Keywords (comma-separated)",
        "keywords_help": "Enter 2-5 keywords separated by commas describing your research interests",
        "keywords_placeholder": "machine learning, neural networks, artificial intelligence",
        "institutions_label": "Select Universities",
        "institutions_help": "Choose universities to search. Select multiple institutions for broader results.",
        "years_label": "Recent Publications Window (Years)",
        "years_help": "Number of years back to search for recent publications that match your keywords",
        "max_per_uni_label": "Max Professors per University",
        "max_per_uni_help": "Limit results to top X professors per university for easier selection",
        "search_button": "🚀 Find Advisors",
        
        # University Categories
        "curated_unis": "🏆 Top Programs",
        "northeast": "🗽 Northeast",
        "southeast": "🌴 Southeast", 
        "midwest": "🌾 Midwest",
        "southwest": "🌵 Southwest",
        "west": "🏔️ West Coast",
        "intl_friendly": "🌎 International Friendly",
        "psychology_top": "🧠 Psychology Programs",
        
        # Results
        "results_title": "📊 Search Results for Shin Ha Eun",
        "results_subtitle": "Great job, Shin Ha Eun! Found {count} professors ranked by research relevance for your search",
        "no_results": "No professors found matching your criteria. Try different keywords or universities.",
        
        # Metrics
        "total_authors": "Total Authors",
        "likely_recruiting": "Likely Recruiting",
        "with_grants": "With Grants Found",
        "avg_score": "Average Relevance",
        
        # Table Headers
        "name": "Name",
        "institution": "Institution", 
        "final_score": "Relevance Score",
        "recent_pubs": "Recent Pubs",
        "active_grants": "Active Grants",
        "recruiting_status": "Recruiting",
        "contact_info": "Contact/Info",
        "research_match": "Research Match",
        
        # Download
        "download_csv": "📥 Download Shin Ha Eun's Results (CSV)",
        "download_help": "Export all results to CSV for Shin Ha Eun's further analysis",
        
        # Status Messages
        "searching": "🔍 Searching for professors for Shin Ha Eun...",
        "found_authors": "✅ Found {count} relevant professors for Shin Ha Eun",
        "processing": "⚙️ Processing Shin Ha Eun's results...",
        "complete": "🎉 Search complete for Shin Ha Eun!",
        
        # Recruiting Status
        "recruiting_yes": "✅",
        "recruiting_no": "❌", 
        "recruiting_unknown": "❓",
        
        # Errors
        "error_no_keywords": "Please enter at least 2 research keywords",
        "error_no_universities": "Please select at least one university",
        "error_search_failed": "Search failed. Please try again.",
        
        # Additional UI Elements
        "how_it_works_title": "🎯 **How Professor Finder Works**",
        "how_it_works_description": "**Professor Finder** helps graduate students discover potential advisors by intelligently matching your research interests with faculty expertise and recent activity.",
        "ranking_process": "**📊 Our Ranking Process:**",
        "concept_matching": "- **Concept Matching (62.5%)**: Semantic analysis of research topics using OpenAlex and MeSH databases",
        "recent_publications": "- **Recent Publications (37.5%)**: Activity in your field based on papers from the past 5 years",
        "smart_filtering": "- **Smart Filtering**: Excludes medical doctors when searching non-medical fields",
        "grant_info": "- **Grant Info**: Funding data shown for reference only (not used in ranking due to reliability issues)",
        "max_professors_label": "Max professors",
        "universities_multiselect": "Universities",
        "search_progress": "Search in progress...",
        "start_search": "Start the intelligent professor search!",
        "complete_form": "Please complete the form above",
        "resolving_institutions": "🏛️ Resolving institutions to ROR IDs...",
        "could_not_resolve": "Could not resolve any institutions. Please check institution names.",
        "resolved_institutions": "Resolved {count} institutions",
        "discovering_researchers": "👥 Discovering researchers...",
        "found_authors_at": "Found {count} authors at {institution}",
        "checking_recruitment": "📢 Checking recruitment signals...",
        "calculating_scores": "📊 Calculating scores...",
        "what_we_care_about": "**🔍 What We Care About:**",
        "research_relevance": "- **Research Relevance**: How closely their work aligns with your keywords", 
        "recent_activity": "- **Recent Activity**: Publications in the last 5 years showing current engagement",
        "university_diversity": "- **University Diversity**: We search across top institutions to give you options",
        "transparency": "- **Transparency**: Every result includes direct links to verify their expertise",
        "limitations_title": "**⚠️ Important Limitations:**",
        "grant_reliability": "- **Grant Data**: May be incomplete or outdated - verify directly with professors",
        "department_gaps": "- **Department Data**: Some professors may not have complete department information",
        "publication_limit": "- **Publications**: Limited to 50 most recent papers per author",
        "manual_verification": "- **Always verify**: Contact professors directly to confirm current availability and interests",
        
        # Psychology App Translations
        "psych_track": "Psychology Track",
        "social_psychology": "Social Psychology",
        "clinical_psychology": "Clinical Psychology",
        "university_ranking": "University Ranking",
        "top_30_universities": "Top 30 US Universities", 
        "top_programs_by_track": "Top Programs by Track",
        "sort_order": "Sort Order",
        "psych_dept_ranking": "Psychology Department Ranking",
        "overall_university_ranking": "Overall University Ranking",
        "acceptance_rate_competitive": "Acceptance Rate (Competitive)",
        "alphabetical": "Alphabetical",
        "data_management": "Data Management",
        "refresh_data": "Refresh Data",
        "export": "Export",
        "csv_download_available": "CSV download available in main program list",
        "data_sources": "Data Sources",
        "how_we_collect_data": "How we collect data",
        "verification": "Verification",
        "understanding_rankings_data": "Understanding Our Rankings & Data",
        "rankings_shown": "Rankings Shown",
        "psychology_dept_rankings": "Psychology Department Rankings (not overall university prestige)",
        "social_psych_programs": "Social Psychology programs ranked by research impact and faculty quality",
        "clinical_psych_programs": "Clinical Psychology programs ranked by APA accreditation and training quality",
        "these_rankings_reflect": "These rankings reflect program strength in your specific field of interest",
        "application_requirements": "Application Requirements",
        "most_requirements_verified": "Most requirements verified directly from university admissions pages",
        "some_data_estimated": "Some data estimated based on typical program patterns - always verify with universities",
        "requirements_change_annually": "Requirements change annually - confirm current details before applying",
        "important_contact_admissions": "Important: Contact admissions offices directly for the most current information",
        "clinical_track": "Clinical Psychology Track",
        "clinical_focus": "Focus: Patient treatment, therapy, clinical research",
        "clinical_acceptance": "Acceptance Rate: 2-5% (EXTREMELY competitive)",
        "clinical_required": "Required: Clinical experience (crisis hotlines, clinics)",
        "clinical_gpa": "GPA: 3.7+ typical",
        "clinical_career": "Career: Licensed psychologist, therapist, clinical researcher",
        "some_universities_no_clinical": "Note: Some universities (Princeton, MIT, etc.) don't have clinical programs!",
        "social_track": "Social Psychology Track",
        "social_focus": "Focus: Population research, social factors, group behavior",
        "social_acceptance": "Acceptance Rate: 8-12% (competitive)",
        "social_required": "Required: Research experience (labs, experiments)",
        "social_gpa": "GPA: 3.5+ typical",
        "social_career": "Career: Professor, researcher, consultant (no patient treatment)",
        "international_requirements": "International Student Requirements",
        "academic": "Academic",
        "english": "English",
        "application": "Application",
        "deadline": "Deadline",
        "gpa_no_minimum": "GPA: No minimum stated",
        "gre_required": "GRE: Required",
        "gre_not_required": "GRE: Not Required",
        "letters": "Letters",
        "fee": "Fee",
        "fall": "Fall",
        "accept": "Accept",
        "top_social_psychology_faculty": "Top Social Psychology Faculty",
        "research_areas": "Research Areas",
        "student_status": "Student Status",
        "accepting": "Accepting",
        "not_accepting": "Not accepting",
        "email": "Email",
        "website": "Website",
        "additional_information": "Additional Information & Data Verification",
        "funding_guaranteed": "Funding guaranteed for admitted students",
        "f1_visa_eligible": "F-1 visa eligible",
        "program_website": "Program Website",
        "admissions_info": "Admissions Info",
        "no_clinical_program": "does NOT have a clinical psychology PhD program",
        "ranking_sources": "Ranking Sources",
        "source": "Source",
        "confidence": "Confidence",
        "methodology": "Methodology",
        "last_verified": "Last verified",
        "primary": "Primary",
        "secondary": "Secondary",
        "apa_database": "APA Database",
        "always_verify_important": "IMPORTANT: Always verify requirements directly with the university. Our data is ~70% accurate for requirements, varies for rankings.",
        "showing_programs": "Showing {count} programs",
        "universities_no_clinical": "{count} universities have NO clinical psychology PhD",
        "no_clinical_programs_explanation": "These universities do not offer clinical psychology PhD programs: {universities}. Consider their other psychology programs or look at different universities for clinical training.",
        "no_programs_found": "No programs found",
        "no_programs_reasons": "This could be because: 1. Data is still loading (check debug info above) 2. Filters are too restrictive 3. Data needs to be refreshed (click 'Refresh Data' in sidebar)",
        "database_contains": "Database contains {count} total programs.",
        "looking_for_universities": "Looking for universities in: {group_type}",
        
        # Additional sidebar translations
        "settings": "Settings",
        "select_track": "Select track:",
        "track_help": "Clinical: Patient treatment, therapy, clinical research\nSocial: Population research, social factors, no patient contact",
        "select_ranking": "Select ranking:",
        "ranking_help": "Overall rankings vs track-specific rankings",
        "refresh_help": "Fetch latest data from university websites",
        "fetching_data": "Fetching latest data... This may take a few minutes",
        "data_refresh_success": "✅ Data refreshed successfully!",
        "data_refresh_error": "Failed to refresh data. Please try again.",
        "data_sources_info": "ℹ️ Data Sources",
        
        # Faculty search tab translations
        "search_faculty_header": "🔍 Search for Social Psychology Faculty",
        "research_keywords_label": "Research keywords:",
        "research_keywords_placeholder": "e.g., implicit bias, social cognition, stereotyping",
        "research_keywords_help": "Enter research topics to find matching faculty",
        "search_button_faculty": "🔍 Search",
        "searching_faculty_info": "Searching for faculty... (This would use the existing search pipeline)",
        "searching_spinner": "Searching...",
        "search_complete_demo": "Search complete! (Demo mode - actual implementation would show results)",
        
        # Compare tab translations  
        "compare_programs_header": "📊 Compare Programs",
        "select_programs_compare": "Select programs to compare (max 5):",
        
        # Documentation tab translations
        "documentation_header": "📖 Documentation", 
        "ranking_methodology": "📊 Ranking Methodology",
        "data_collection_tab": "🔍 Data Collection",
        "data_freshness_tab": "📅 Data Freshness",
    },
    
    "ko": {
        # Main UI
        "app_title": "🎓 프로페서 파인더 - 대학원 지도교수 발견",
        "app_subtitle": "환영합니다, 신하은님! 연구 전문성과 가용성을 바탕으로 완벽한 대학원 지도교수를 찾아보세요",
        "language_toggle": "언어",
        
        # Search Form
        "search_form_title": "🔍 검색 조건",
        "keywords_label": "연구 키워드 (쉼표로 구분)",
        "keywords_help": "연구 관심사를 설명하는 2-5개의 키워드를 쉼표로 구분하여 입력하세요",
        "keywords_placeholder": "기계학습, 신경망, 인공지능",
        "institutions_label": "대학 선택",
        "institutions_help": "검색할 대학을 선택하세요. 더 넓은 결과를 위해 여러 대학을 선택할 수 있습니다.",
        "years_label": "최근 논문 검색 범위 (년)",
        "years_help": "키워드와 일치하는 최근 논문을 검색할 과거 년수",
        "max_per_uni_label": "대학당 최대 교수 수",
        "max_per_uni_help": "대학별로 상위 X명의 교수만 표시하여 선택을 용이하게 함",
        "search_button": "🚀 지도교수 찾기",
        
        # University Categories  
        "curated_unis": "🏆 최고 프로그램",
        "northeast": "🗽 동북부",
        "southeast": "🌴 남동부", 
        "midwest": "🌾 중서부",
        "southwest": "🌵 남서부",
        "west": "🏔️ 서부",
        "intl_friendly": "🌎 국제학생 친화적",
        "psychology_top": "🧠 심리학 프로그램",
        
        # Results
        "results_title": "📊 신하은님을 위한 검색 결과",
        "results_subtitle": "잘하셨어요, 신하은님! 당신의 검색에 대해 연구 관련성으로 순위를 매긴 {count}명의 교수를 찾았습니다",
        "no_results": "검색 조건에 맞는 교수를 찾지 못했습니다. 다른 키워드나 대학을 시도해보세요.",
        
        # Metrics
        "total_authors": "총 교수 수",
        "likely_recruiting": "학생 모집 가능성",
        "with_grants": "연구비 보유",
        "avg_score": "평균 관련성",
        
        # Table Headers
        "name": "이름",
        "institution": "소속 대학",
        "final_score": "관련성 점수", 
        "recent_pubs": "최근 논문",
        "active_grants": "활성 연구비",
        "recruiting_status": "학생 모집",
        "contact_info": "연락처/정보",
        "research_match": "연구 일치도",
        
        # Download
        "download_csv": "📥 신하은님의 결과 다운로드 (CSV)",
        "download_help": "신하은님의 추가 분석을 위해 모든 결과를 CSV로 내보내기",
        
        # Status Messages
        "searching": "🔍 신하은님을 위한 교수 검색 중...",
        "found_authors": "✅ 신하은님을 위한 {count}명의 관련 교수를 찾았습니다",
        "processing": "⚙️ 신하은님의 결과 처리 중...",
        "complete": "🎉 신하은님의 검색이 완료되었습니다!",
        
        # Recruiting Status
        "recruiting_yes": "✅",
        "recruiting_no": "❌",
        "recruiting_unknown": "❓",
        
        # Errors
        "error_no_keywords": "최소 2개의 연구 키워드를 입력해주세요",
        "error_no_universities": "최소 하나의 대학을 선택해주세요", 
        "error_search_failed": "검색에 실패했습니다. 다시 시도해주세요.",
        
        # Additional UI Elements
        "how_it_works_title": "🎯 프로페서 파인더의 작동 원리",
        "how_it_works_description": "프로페서 파인더는 연구 관심사를 교수진 전문성 및 최근 활동과 지능적으로 매칭하여 대학원생들이 잠재적 지도교수를 발견할 수 있도록 도와줍니다.",
        "ranking_process": "📊 순위 매기기 과정:",
        "concept_matching": "개념 매칭 (62.5%): OpenAlex 및 MeSH 데이터베이스를 사용한 연구 주제의 의미적 분석",
        "recent_publications": "최근 논문 (37.5%): 지난 5년간 논문을 기반으로 한 해당 분야 활동",
        "smart_filtering": "스마트 필터링: 비의료 분야 검색 시 의사 제외",
        "grant_info": "연구비 정보: 신뢰성 문제로 순위에는 사용되지 않고 참고용으로만 표시",
        "max_professors_label": "최대 교수 수",
        "universities_multiselect": "대학교",
        "search_progress": "검색 진행 중...",
        "start_search": "지능형 교수 검색을 시작하세요!",
        "complete_form": "위의 양식을 완성해주세요",
        "resolving_institutions": "🏛️ 대학을 ROR ID로 변환 중...",
        "could_not_resolve": "대학을 확인할 수 없습니다. 대학 이름을 확인해주세요.",
        "resolved_institutions": "{count}개 대학을 확인했습니다",
        "discovering_researchers": "👥 연구자 발견 중...",
        "found_authors_at": "{institution}에서 {count}명의 교수를 찾았습니다",
        "checking_recruitment": "📢 모집 신호 확인 중...",
        "calculating_scores": "📊 점수 계산 중...",
        "what_we_care_about": "**🔍 중요하게 고려하는 요소:**",
        "research_relevance": "- **연구 관련성**: 그들의 연구가 당신의 키워드와 얼마나 밀접하게 일치하는지",
        "recent_activity": "- **최근 활동**: 현재 참여도를 보여주는 지난 5년간의 논문 발표",
        "university_diversity": "- **대학 다양성**: 최고의 기관들을 검색하여 다양한 선택지를 제공",
        "transparency": "- **투명성**: 모든 결과에는 전문성을 확인할 수 있는 직접 링크 포함",
        "limitations_title": "**⚠️ 중요한 제한사항:**",
        "grant_reliability": "- **연구비 데이터**: 불완전하거나 오래된 정보일 수 있음 - 교수에게 직접 확인 필요",
        "department_gaps": "- **소속 부서 데이터**: 일부 교수의 소속 부서 정보가 불완전할 수 있음",
        "publication_limit": "- **논문**: 저자당 최근 50편의 논문으로 제한",
        "manual_verification": "- **항상 확인**: 현재 가용성과 관심사를 확인하기 위해 교수에게 직접 연락",
        
        # Psychology App Korean Translations
        "psych_track": "심리학 전공",
        "social_psychology": "사회심리학",
        "clinical_psychology": "임상심리학",
        "university_ranking": "대학 순위",
        "top_30_universities": "미국 상위 30대 대학", 
        "top_programs_by_track": "전공별 상위 프로그램",
        "sort_order": "정렬 순서",
        "psych_dept_ranking": "심리학과 순위",
        "overall_university_ranking": "전체 대학 순위",
        "acceptance_rate_competitive": "합격률 (경쟁도)",
        "alphabetical": "알파벳순",
        "data_management": "데이터 관리",
        "refresh_data": "데이터 새로고침",
        "export": "내보내기",
        "csv_download_available": "메인 프로그램 목록에서 CSV 다운로드 가능",
        "data_sources": "데이터 소스",
        "how_we_collect_data": "데이터 수집 방법",
        "verification": "검증",
        "understanding_rankings_data": "순위 및 데이터 이해하기",
        "rankings_shown": "표시된 순위",
        "psychology_dept_rankings": "심리학과 순위 (전체 대학 순위가 아님)",
        "social_psych_programs": "연구 영향력과 교수진 품질을 기준으로 한 사회심리학 프로그램 순위",
        "clinical_psych_programs": "APA 인증과 훈련 품질을 기준으로 한 임상심리학 프로그램 순위",
        "these_rankings_reflect": "이 순위는 귀하의 특정 관심 분야에서의 프로그램 강점을 반영합니다",
        "application_requirements": "지원 요건",
        "most_requirements_verified": "대부분의 요건이 대학 입학 사무실 페이지에서 직접 확인됨",
        "some_data_estimated": "일부 데이터는 일반적인 프로그램 패턴을 기반으로 추정됨 - 항상 대학에 확인하세요",
        "requirements_change_annually": "요건은 매년 변경됩니다 - 지원 전에 현재 세부사항을 확인하세요",
        "important_contact_admissions": "중요: 최신 정보는 입학 사무실에 직접 문의하세요",
        "clinical_track": "임상심리학 전공",
        "clinical_focus": "초점: 환자 치료, 치료법, 임상 연구",
        "clinical_acceptance": "합격률: 2-5% (극도로 경쟁적)",
        "clinical_required": "필수: 임상 경험 (위기 상담 전화, 클리닉 자원봉사)",
        "clinical_gpa": "학점: 3.7+ 일반적",
        "clinical_career": "진로: 면허 심리학자, 치료사, 임상 연구자",
        "some_universities_no_clinical": "참고: 일부 대학(프린스턴, MIT 등)은 임상 프로그램이 없습니다!",
        "social_track": "사회심리학 전공",
        "social_focus": "초점: 인구 연구, 사회 요인, 집단 행동",
        "social_acceptance": "합격률: 8-12% (경쟁적)",
        "social_required": "필수: 연구 경험 (실험실, 실험)",
        "social_gpa": "학점: 3.5+ 일반적",
        "social_career": "진로: 교수, 연구자, 컨설턴트 (환자 치료 없음)",
        "international_requirements": "국제학생 입학 요건",
        "academic": "학업",
        "english": "영어",
        "application": "지원",
        "deadline": "마감일",
        "gpa_no_minimum": "학점: 최소 기준 없음",
        "gre_required": "GRE: 필수",
        "gre_not_required": "GRE: 필수 아님",
        "letters": "추천서",
        "fee": "수수료",
        "fall": "가을학기",
        "accept": "합격률",
        "top_social_psychology_faculty": "상위 사회심리학 교수진",
        "research_areas": "연구 분야",
        "student_status": "학생 수용 상태",
        "accepting": "수용 중",
        "not_accepting": "수용 안함",
        "email": "이메일",
        "website": "웹사이트",
        "additional_information": "추가 정보 및 데이터 검증",
        "funding_guaranteed": "입학생 펀딩 보장",
        "f1_visa_eligible": "F-1 비자 자격",
        "program_website": "프로그램 웹사이트",
        "admissions_info": "입학 정보",
        "no_clinical_program": "는 임상심리학 박사 프로그램이 없습니다",
        "ranking_sources": "순위 소스",
        "source": "출처",
        "confidence": "신뢰도",
        "methodology": "방법론",
        "last_verified": "마지막 확인",
        "primary": "주요",
        "secondary": "보조",
        "apa_database": "APA 데이터베이스",
        "always_verify_important": "중요: 항상 대학에 직접 요건을 확인하세요. 우리 데이터는 요건에 대해 ~70% 정확하며, 순위는 다양합니다.",
        "showing_programs": "{count}개 프로그램 표시 중",
        "universities_no_clinical": "{count}개 대학은 임상심리학 박사과정이 없습니다",
        "no_clinical_programs_explanation": "다음 대학들은 임상심리학 박사 프로그램을 제공하지 않습니다: {universities}. 다른 심리학 프로그램을 고려하거나 임상 훈련을 위해 다른 대학을 찾아보세요.",
        "no_programs_found": "프로그램을 찾을 수 없습니다",
        "no_programs_reasons": "이는 다음과 같은 이유일 수 있습니다: 1. 데이터가 여전히 로딩 중 (위의 디버그 정보 확인) 2. 필터가 너무 제한적 3. 데이터를 새로고침해야 함 (사이드바의 '데이터 새로고침' 클릭)",
        "database_contains": "데이터베이스에 총 {count}개 프로그램이 있습니다.",
        "looking_for_universities": "다음에서 대학을 찾는 중: {group_type}",
        
        # Additional sidebar translations Korean
        "settings": "설정",
        "select_track": "전공 선택:",
        "track_help": "임상: 환자 치료, 치료법, 임상 연구\n사회: 인구 연구, 사회적 요인, 환자 접촉 없음",
        "select_ranking": "순위 선택:",
        "ranking_help": "전체 순위 vs 전공별 순위",
        "refresh_help": "대학 웹사이트에서 최신 데이터 가져오기",
        "fetching_data": "최신 데이터를 가져오는 중... 몇 분이 걸릴 수 있습니다",
        "data_refresh_success": "✅ 데이터가 성공적으로 새로고침되었습니다!",
        "data_refresh_error": "데이터 새로고침에 실패했습니다. 다시 시도해주세요.",
        "data_sources_info": "ℹ️ 데이터 소스",
        
        # Faculty search tab translations Korean
        "search_faculty_header": "🔍 사회심리학 교수 검색",
        "research_keywords_label": "연구 키워드:",
        "research_keywords_placeholder": "예: 암묵적 편견, 사회 인지, 고정관념",
        "research_keywords_help": "일치하는 교수를 찾기 위해 연구 주제를 입력하세요",
        "search_button_faculty": "🔍 검색",
        "searching_faculty_info": "교수 검색 중... (기존 검색 파이프라인 사용)",
        "searching_spinner": "검색 중...",
        "search_complete_demo": "검색 완료! (데모 모드 - 실제 구현시 결과 표시)",
        
        # Compare tab translations Korean
        "compare_programs_header": "📊 프로그램 비교",
        "select_programs_compare": "비교할 프로그램 선택 (최대 5개):",
        
        # Documentation tab translations Korean
        "documentation_header": "📖 문서",
        "ranking_methodology": "📊 순위 방법론", 
        "data_collection_tab": "🔍 데이터 수집",
        "data_freshness_tab": "📅 데이터 최신성",
    }
}

def get_text(key: str, lang: str = "en", **kwargs) -> str:
    """Get translated text for the given key and language."""
    text = TRANSLATIONS.get(lang, TRANSLATIONS["en"]).get(key, key)
    if kwargs:
        return text.format(**kwargs)
    return text